### ISSUE TITLE
Not running on Android

### ISSUE THREAD

**Issue by quetool** [zhouzaihang/flutter_hand_tracking_plugin#11]
Hi, I am not being able to run the project on Android
What I do:
```
cd example/
flutter run -d {android_device_id} -v
```

And this are the last lines of the output

```
[        ] > Task :app:processDebugResources FAILED
[  +96 ms] FAILURE: Build failed with an exception.
[   +4 ms] * What went wrong:
[        ] Execution failed for task ':app:processDebugResources'.
[        ] > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
[        ]    > Failed to transform file 'hand_tracking_aar.aar' to match attributes {artifactType=android-compiled-dependencies-resources}
[        ]       > Execution failed for AarResourcesCompilerTransform:
/Users/alfredorinaudo/.gradle/caches/transforms-2/files-2.1/f288be8ddaa4d301a851bc5959afacdc/jetified-hand_tracking_aar.
[   +1 ms]          > /Users/alfredorinaudo/.gradle/caches/transforms-2/files-2.1/f288be8ddaa4d301a851bc5959afacdc/jetified-hand_tracking_aar/AndroidManifest.xml
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[  +20 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 49s
[        ] 25 actionable tasks: 6 executed, 19 up-to-date
[ +608 ms] Running Gradle task 'assembleDebug'... (completed in 50.6s)
[   +9 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 58,413ms.
[   +9 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:607:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:977:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
           #21     _rootRunUnary (dart:async/zone.dart:1198:47)
           #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #28     _rootRun (dart:async/zone.dart:1190:13)
           #29     _CustomZone.run (dart:async/zone.dart:1093:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +221 ms] ensureAnalyticsSent: 219ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +3 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

I checked and `hand_tracking_aar.aar` is on `flutter_hand_tracking_plugin-master/android/libs/hand_tracking_aar.aar`

**Comment by zhouzaihang** [comment]
You can try to check if the file  'hand_tracking_aar.aar'  exists in the
path(flutter_hand_tracking_plugin/android/libs/hand_tracking_aar.aar)
https://github.com/zhouzaihang/flutter_hand_tracking_plugin/blob/master/android/libs/hand_tracking_aar.aar

Because it stored in git lfs. Git Large File Storage (LFS) replaces large
files such as ('hand_tracking_aar.aar') with text pointers inside Git,
while storing the file contents on a remote server like GitHub.com or
GitHub Enterprise.

If it does not exist, or exists as a link, you need to install `git lfs`
to get it.You also could downloaded the .aar file into the path, and then
rebuild the project.

**Comment by quetool** [comment]
Thanks for answering but like I said before the file is indeed on the correct path.

**Comment by quetool** [comment]
```
Downloading android/libs/hand_tracking_aar.aar (106 MB)
Error downloading object: android/libs/hand_tracking_aar.aar (e9e16b6): Smudge error: Error downloading android/libs/hand_tracking_aar.aar (e9e16b67719b7f6a53ec6295764d4c5a05f25b09ddfdefb165da2ebcfd60e9d2): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Errors logged to /Users/alfredorinaudo/Development/Projects/Flutter/flutter_hand_tracking_plugin/.git/lfs/logs/20210106T125119.662904.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: android/libs/hand_tracking_aar.aar: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by quetool** [comment]
I am closing this issue cause I saw the answer on a few other issues. Sorry to bother, I will came back if something goes wrong! Thanks!
